### ISSUE TITLE
Access to Copilot

### ISSUE THREAD

**Issue by Swati-Aravind** [Netapp-Copilot/new-user#1019]
### Netapp Username

aras

**Comment by Netapp-audit** [comment]
Hi @Swati-Aravind, welcome back to Copilot!!!

**Comment by Swati-Aravind** [comment]
Request to reactivate copilot license for testing and automation work

**Comment by Netapp-audit** [comment]
Hi @Swati-Aravind, Your account has been reactivated. You should now have access to Copilot.

**Comment by Netapp-audit** [comment]
User Swati-Aravind has been added to Copilot.
For SecLab/BigTop users there are special steps on the confluence page that need to be followed to complete the setup https://confluence.ngage.netapp.com/display/NGAGE/Copilot
For OpenLab users please follow the standard steps here https://docs.github.com/en/copilot/using-github-copilot/getting-code-suggestions-in-your-ide-with-github-copilot
