### ISSUE TITLE
Access to Copilot

### ISSUE THREAD

**Issue by JyothiArjilli** [Netapp-Copilot/new-user#139]
### Netapp Username

jyothi arjilli

**Comment by Netapp-audit** [comment]
Hi @JyothiArjilli, welcome to Copilot!!! As a new user, please make sure your NetApp Email address <username>@netapp.com is listed as one of your emails here. https://github.com/settings/emails. If not, you will receive an SSO error when logging in to join the org.

**Comment by carchi8py** [comment]
@JyothiArjilli can you fill this out again with your netapp username.
