### ISSUE TITLE
Access to Copilot

### ISSUE THREAD

**Issue by MarioRuiz** [Netapp-Copilot/new-user#163]
### Netapp Username

rmario

**Comment by Netapp-audit** [comment]
User MarioRuiz has been added to Copilot.
For SecLab/BigTop users there are special steps on the confluence page that need to be followed to complete the setup https://confluence.ngage.netapp.com/display/NGAGE/Copilot
For OpenLab users please follow the standard steps here https://docs.github.com/en/copilot/using-github-copilot/getting-code-suggestions-in-your-ide-with-github-copilot
