### ISSUE TITLE
Access to Copilot

### ISSUE THREAD

**Issue by rajanees** [Netapp-Copilot/new-user#167]
### Netapp Username

rajanees

**Comment by rajanees** [comment]
Please enable access to Copilot

Thanks,
Rajaneesh

**Comment by Netapp-audit** [comment]
User rajanees has been added to Copilot.
For SecLab/BigTop users there are special steps on the confluence page that need to be followed to complete the setup https://confluence.ngage.netapp.com/display/NGAGE/Copilot
For OpenLab users please follow the standard steps here https://docs.github.com/en/copilot/using-github-copilot/getting-code-suggestions-in-your-ide-with-github-copilot
