### ISSUE TITLE
Access to Copilot

### ISSUE THREAD

**Issue by UTKARSH-REAPER** [Netapp-Copilot/new-user#285]
### Netapp Username

UTKARSH-REAPER

**Comment by Netapp-audit** [comment]
Hi @UTKARSH-REAPER, welcome to Copilot!!! As a new user, please make sure your NetApp Email address <username>@netapp.com is listed as one of your emails here. https://github.com/settings/emails. If not, you will receive an SSO error when logging in to join the org.

**Comment by Netapp-audit** [comment]
Hi @UTKARSH-REAPER, You have been added to ng-github-user, In about an hour you will receive an email from GitHub with an invite to the Netapp-copilot org. The email address will be from noreply@github.com You must accept the invite to get access to Copilot. The email may be in your junk mail folder. Once Accepted you will have access to Copilot.

**Comment by UTKARSH-REAPER** [comment]
Still haven't received any updates

**Comment by UTKARSH-REAPER** [comment]
I'm seeing this when I'm trying to Join @Netapp-Copilot. 
Request Id: 13927632-ab5d-40a8-88a7-c9bac5689c00
Correlation Id: 2d2b7d72-1e68-48bc-8764-c17210e0e4f8
Timestamp: 2024-09-29T15:21:01Z
Message: AADSTS50105: Your administrator has configured the application Github Enterprise | SAML | PROD ('5f247685-2052-4822-a376-1f2bbb9f5f7b') to block users unless they are specifically granted ('assigned') access to the application. The signed in user 'utkarsh1@netapp.com' is blocked because they are not a direct member of a group with access, nor had access directly assigned by an administrator. Please contact your administrator to assign access to this application.
