### ISSUE TITLE
Access to Copilot

### ISSUE THREAD

**Issue by harshsinghnetapp** [Netapp-Copilot/new-user#341]
### Netapp Username

harsh2

**Comment by Netapp-audit** [comment]
Hi @harshsinghnetapp, welcome to Copilot!!! As a new user, please make sure your NetApp Email address <username>@netapp.com is listed as one of your emails here. https://github.com/settings/emails. If not, you will receive an SSO error when logging in to join the org.

**Comment by Netapp-audit** [comment]
Hi @harshsinghnetapp, You have been added to ng-github-user, In about an hour you will receive an email from GitHub with an invite to the Netapp-copilot org. The email address will be from noreply@github.com You must accept the invite to get access to Copilot. The email may be in your junk mail folder. Once Accepted you will have access to Copilot.

**Comment by Netapp-audit** [comment]
User harshsinghnetapp has been added to Copilot.
For SecLab/BigTop users there are special steps on the confluence page that need to be followed to complete the setup https://confluence.ngage.netapp.com/display/NGAGE/Copilot
For OpenLab users please follow the standard steps here https://docs.github.com/en/copilot/using-github-copilot/getting-code-suggestions-in-your-ide-with-github-copilot

**Comment by harshsinghnetapp** [comment]
Hi,
I am getting this error while accepting the invite:
"There was an issue joining the enterprise: Your GitHub user account @harshsinghnetapp is currently unlinked. However, you are attempting to authenticate with your Identity Provider using the 'HARSH.SINGH@netapp.com' SAML identity which is already linked to a different GitHub user account in the organization. Please reach out to one of your GitHub organization owners for assistance. "



I had an earlier github account the id @harshvikramsingh linked to Netapp email, but I seemed to have lost its credentials. Hence created this new github account today @harshsinghnetapp. Any way to UNLINK my ID HARSH.SINGH@netapp.com to my old github account @harshvikramsingh?
