### ISSUE TITLE
Access to Copilot

### ISSUE THREAD

**Issue by fewaffles** [Netapp-Copilot/new-user#48]
### Netapp Username

redacted

**Comment by Netapp-audit** [comment]
Hi @fewaffles, welcome to Copilot!!! As a new user, please make sure your NetApp Email address <username>@netapp.com is listed as one of your emails here. https://github.com/settings/emails. If not, you will receive an SSO error when logging in to join the org.

**Comment by Netapp-audit** [comment]
Hi @fewaffles, You have been added to ng-github-user, In about an hour you will receive an email from GitHub with an invite to the Netapp-copilot org. The email address will be from noreply@github.com You must accept the invite to get access to Copilot. The email may be in your junk mail folder. Once Accepted you will have access to Copilot.

**Comment by chuyich** [comment]
Invitation has been sent. Please check.
