### ISSUE TITLE
Access to Copilot

### ISSUE THREAD

**Issue by Andrewpk** [Netapp-Copilot/new-user#539]
### Netapp Username

akehrig

**Comment by Andrewpk** [comment]
I have my own yearly copilot sub, but I wanted to make sure I was enrolled in the enterprise plan in case there are specific netapp copilot settings that are overridden.

**Comment by Netapp-audit** [comment]
User Andrewpk has been added to Copilot.
For SecLab/BigTop users there are special steps on the confluence page that need to be followed to complete the setup https://confluence.ngage.netapp.com/display/NGAGE/Copilot
For OpenLab users please follow the standard steps here https://docs.github.com/en/copilot/using-github-copilot/getting-code-suggestions-in-your-ide-with-github-copilot
