### ISSUE TITLE
Access to Copilot

### ISSUE THREAD

**Issue by aakash2khot** [Netapp-Copilot/new-user#67]
### Netapp Username

kaakash

**Comment by Netapp-audit** [comment]
Hi @aakash2khot, welcome to Copilot!!! As a new user, please make sure your NetApp Email address <username>@netapp.com is listed as one of your emails here. https://github.com/settings/emails. If not, you will receive an SSO error when logging in to join the org.

**Comment by Netapp-audit** [comment]
User aakash2khot has been added to Copilot.
For SecLab/BigTop users there are special steps on the confluence page that need to be followed to complete the setup https://confluence.ngage.netapp.com/display/NGAGE/Copilot
For OpenLab users please follow the standard steps here https://docs.github.com/en/copilot/using-github-copilot/getting-code-suggestions-in-your-ide-with-github-copilot
