### ISSUE TITLE
Access to Copilot

### ISSUE THREAD

**Issue by aravindcgit** [Netapp-Copilot/new-user#847]
### Netapp Username

aravindc

**Comment by Netapp-audit** [comment]
Hi @aravindcgit, welcome back to Copilot!!!

**Comment by Netapp-audit** [comment]
Hi @aravindcgit, Your account has been reactivated. You should now have access to Copilot.

**Comment by aravindcgit** [comment]
My access to coilot has expired. Please reactivate the access.
